services:
  - type: web
    name: ai-news-analyzer
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATA_DIR
        value: /tmp/bank_news_data
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.playwright
