#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Bank Configuration Patterns
Auto-generated on 2025-08-06 09:05:31
Generated by Enhanced Bank Configuration System
"""

BANK_CONFIGS = {
    'gulf_bank': {
        'official_english': 'Gulf Bank',
        'english_name': 'Gulf Bank',
        'official_arabic': 'بنك الخليج',
        'arabic_name': 'بنك الخليج',
        'abbreviations': ['GBK', 'Gulf Bk'],
        'high_confidence_patterns': ['\\bGulf\\ Bank\\b', 'بنك\\ الخليج', '"بنك\\ الخليج"', '"Gulf\\ Bank"', '\\bGBK\\b', '\\bGulf\\ Bank\\s+Sponsorship\\b', 'بنك\\ الخليج\\s+رعاية', 'رعاية.*?بنك\\ الخليج', '«GBK».*?(?:بنك|مصرف|رعا)'],
        'medium_confidence_patterns': ['\\bGulf\\s+Bank\\b', 'الخليج.*?(?:اختتم|افتتح|تنظيم|رعاية)', '(?:اختتم|افتتح|تنظيم|رعاية).*?الخليج', '(?:رعاية|تنظيم|برنامج).*?الخليج'],
        'exclusion_patterns': ['\\bGulf\\s+Region\\b', '\\bGulf\\s+countries\\b', 'بورصة.*?الخليج', 'أسواق.*?الخليج', '\\bGulf\\s+countries\\b', '\\bGulf\\s+states\\b', '\\bGCC\\b', '\\bArabian\\s+Gulf\\b', '\\bPersian\\s+Gulf\\b', 'دول\\s+الخليج', 'مجلس\\s+التعاون\\s+الخليجي', 'الخليج\\s+العربي', 'منطقة\\s+الخليج'],
        'common_contexts': ['Financial reports', 'Sponsorship announcements', 'Banking events', 'Stock market updates'],
        'validation_status': 'ACTIVE'
    },
    'nbk': {
        'official_english': 'National Bank of Kuwait',
        'english_name': 'National Bank of Kuwait',
        'official_arabic': 'البنك الوطني الكويتي',
        'arabic_name': 'البنك الوطني الكويتي',
        'abbreviations': ['NBK', 'N.B.K.', 'الوطني'],
        'high_confidence_patterns': ['\\bNational\\ Bank\\ of\\ Kuwait\\b', 'البنك\\ الوطني\\ الكويتي', '"البنك\\ الوطني\\ الكويتي"', '"National\\ Bank\\ of\\ Kuwait"', '\\bNBK\\b', '\\bN\\.B\\.K\\.\\b', '\\bالوطني\\b', '\\bNational\\ Bank\\ of\\ Kuwait\\s+Sponsorship\\b', 'البنك\\ الوطني\\ الكويتي\\s+رعاية', 'رعاية.*?البنك\\ الوطني\\ الكويتي', '«NBK».*?(?:بنك|مصرف|رعا)'],
        'medium_confidence_patterns': ['\\bNational\\s+Kuwait\\b', '\\bNational\\s+Bank\\s+Kuw\\b', 'الكويتي.*?(?:اختتم|افتتح|تنظيم|رعاية)', '(?:اختتم|افتتح|تنظيم|رعاية).*?الكويتي', '(?:رعاية|تنظيم|برنامج).*?الكويتي'],
        'exclusion_patterns': ['\\bNational\\s+Region\\b', '\\bNational\\s+countries\\b', 'بورصة.*?الكويتي', 'أسواق.*?الكويتي', '\\bNational\\s+Bank\\b(?!\\s+of\\s+Kuwait)', 'البنك\\s+الوطني(?!\\s+الكويتي)', '\\bKuwait\\b(?!\\s+National\\s+Bank)'],
        'common_contexts': ['Financial reports', 'Sponsorship announcements', 'Economic news', 'Banking sector analysis'],
        'validation_status': 'ACTIVE'
    },
    'kfh': {
        'official_english': 'Kuwait Finance House',
        'english_name': 'Kuwait Finance House',
        'official_arabic': 'بيت التمويل الكويتي',
        'arabic_name': 'بيت التمويل الكويتي',
        'abbreviations': ['KFH', 'K.F.H.', 'التمويل'],
        'high_confidence_patterns': ['\\bKuwait\\ Finance\\ House\\b', 'بيت\\ التمويل\\ الكويتي', '"بيت\\ التمويل\\ الكويتي"', '"Kuwait\\ Finance\\ House"', '\\bKFH\\b', '\\bK\\.F\\.H\\.\\b', '\\bالتمويل\\b', '\\bKuwait\\ Finance\\ House\\s+Sponsorship\\b', 'بيت\\ التمويل\\ الكويتي\\s+رعاية', 'رعاية.*?بيت\\ التمويل\\ الكويتي', '«KFH».*?(?:بنك|مصرف|رعا)'],
        'medium_confidence_patterns': ['\\bKuwait\\s+House\\b', '\\bKuwait\\s+Finance\\s+Hou\\b', 'الكويتي.*?(?:اختتم|افتتح|تنظيم|رعاية)', '(?:اختتم|افتتح|تنظيم|رعاية).*?الكويتي', '(?:رعاية|تنظيم|برنامج).*?الكويتي'],
        'exclusion_patterns': ['\\bKuwait\\s+Region\\b', '\\bKuwait\\s+countries\\b', 'بورصة.*?الكويتي', 'أسواق.*?الكويتي', '\\bFinance\\s+House\\b(?!\\s+Kuwait)', 'بيت\\s+التمويل(?!\\s+الكويتي)', '\\bKuwait\\s+Finance\\s+Company\\b'],
        'common_contexts': ['Islamic banking', 'Financial reports', 'Sponsorship events', 'Real estate investments'],
        'validation_status': 'ACTIVE'
    },
    # Add this to the BANK_CONFIGS dictionary in bank_patterns.py

        'boubyan_bank': {
            'official_english': 'Boubyan Bank',
            'english_name': 'Boubyan Bank', 
            'official_arabic': 'بنك بوبيان',
            'arabic_name': 'بنك بوبيان',
            'abbreviations': ['Boubyan', 'بوبيان', 'BBK'],
            'high_confidence_patterns': [
                '\\bBoubyan\\ Bank\\b', 'بنك\\ بوبيان', '"بنك\\ بوبيان"', '"Boubyan\\ Bank"', 
                '\\bBoubyan\\b', '\\bبوبيان\\b', '\\bBBK\\b',
                '\\bBoubyan\\ Bank\\s+Sponsorship\\b', 'بنك\\ بوبيان\\s+رعاية', 
                'رعاية.*?بنك\\ بوبيان', '«Boubyan».*?(?:بنك|مصرف|رعا)',
                '«بوبيان».*?(?:بنك|مصرف|رعا)'
            ],
            'medium_confidence_patterns': [
                '\\bBoubyan\\s+Bank\\b', 'بوبيان.*?(?:اختتم|افتتح|تنظيم|رعاية)', 
                '(?:اختتم|افتتح|تنظيم|رعاية).*?بوبيان', '(?:رعاية|تنظيم|برنامج).*?بوبيان',
                'البنك.*?بوبيان', 'بوبيان.*?البنك'
            ],
            'exclusion_patterns': [
                '\\bBoubyan\\s+Region\\b', '\\bBoubyan\\s+countries\\b', 
                'بورصة.*?بوبيان', 'أسواق.*?بوبيان'
            ],
            'common_contexts': ['Islamic banking', 'Digital banking', 'Retail banking', 'Corporate finance', 'Real estate financing'],
            'validation_status': 'ACTIVE'
        },
    'cbk': {
        'official_english': 'Commercial Bank of Kuwait',
        'english_name': 'Commercial Bank of Kuwait',
        'official_arabic': 'البنك التجاري الكويتي',
        'arabic_name': 'البنك التجاري الكويتي',
        'abbreviations': ['CBK', 'C.B.K.', 'التجاري'],
        'high_confidence_patterns': ['\\bCommercial\\ Bank\\ of\\ Kuwait\\b', 'البنك\\ التجاري\\ الكويتي', '"البنك\\ التجاري\\ الكويتي"', '"Commercial\\ Bank\\ of\\ Kuwait"', '\\bCBK\\b', '\\bC\\.B\\.K\\.\\b', '\\bالتجاري\\b', '\\bCommercial\\ Bank\\ of\\ Kuwait\\s+Sponsorship\\b', 'البنك\\ التجاري\\ الكويتي\\s+رعاية', 'رعاية.*?البنك\\ التجاري\\ الكويتي', '«CBK».*?(?:بنك|مصرف|رعا)'],
        'medium_confidence_patterns': ['\\bCommercial\\s+Kuwait\\b', '\\bCommercial\\s+Bank\\s+Kuw\\b', 'الكويتي.*?(?:اختتم|افتتح|تنظيم|رعاية)', '(?:اختتم|افتتح|تنظيم|رعاية).*?الكويتي', '(?:رعاية|تنظيم|برنامج).*?الكويتي'],
        'exclusion_patterns': ['\\bCommercial\\s+Region\\b', '\\bCommercial\\s+countries\\b', 'بورصة.*?الكويتي', 'أسواق.*?الكويتي'],
        'common_contexts': ['Commercial banking', 'Business financing', 'Corporate banking', 'Trade finance'],
        'validation_status': 'READY'
    },
    'burgan_bank': {
        'official_english': 'Burgan Bank',
        'english_name': 'Burgan Bank',
        'official_arabic': 'بنك برقان',
        'arabic_name': 'بنك برقان',
        'abbreviations': ['Burgan', 'برقان'],
        'high_confidence_patterns': ['\\bBurgan\\ Bank\\b', 'بنك\\ برقان', '"بنك\\ برقان"', '"Burgan\\ Bank"', '\\bBurgan\\b', '\\bبرقان\\b', '\\bBurgan\\ Bank\\s+Sponsorship\\b', 'بنك\\ برقان\\s+رعاية', 'رعاية.*?بنك\\ برقان', '«Burgan».*?(?:بنك|مصرف|رعا)'],
        'medium_confidence_patterns': ['\\bBurgan\\s+Bank\\b', 'برقان.*?(?:اختتم|افتتح|تنظيم|رعاية)', '(?:اختتم|افتتح|تنظيم|رعاية).*?برقان', '(?:رعاية|تنظيم|برنامج).*?برقان'],
        'exclusion_patterns': ['\\bBurgan\\s+Region\\b', '\\bBurgan\\s+countries\\b', 'بورصة.*?برقان', 'أسواق.*?برقان'],
        'common_contexts': ['Retail banking', 'Personal banking', 'Digital banking', 'Consumer loans'],
        'validation_status': 'READY'
    },
    'kib': {
        'official_english': 'Kuwait International Bank',
        'english_name': 'Kuwait International Bank',
        'official_arabic': 'بنك الكويت الدولي',
        'arabic_name': 'بنك الكويت الدولي',
        'abbreviations': ['KIB', 'K.I.B.', 'الكويت الدولي'],
        'high_confidence_patterns': ['\\bKuwait\\ International\\ Bank\\b', 'بنك\\ الكويت\\ الدولي', '"بنك\\ الكويت\\ الدولي"', '"Kuwait\\ International\\ Bank"', '\\bKIB\\b', '\\bK\\.I\\.B\\.\\b', '\\bKuwait\\ International\\ Bank\\s+Sponsorship\\b', 'بنك\\ الكويت\\ الدولي\\s+رعاية', 'رعاية.*?بنك\\ الكويت\\ الدولي', '«KIB».*?(?:بنك|مصرف|رعا)'],
        'medium_confidence_patterns': ['\\bKuwait\\s+Bank\\b', '\\bKuwait\\s+International\\s+Ban\\b', 'الدولي.*?(?:اختتم|افتتح|تنظيم|رعاية)', '(?:اختتم|افتتح|تنظيم|رعاية).*?الدولي', '(?:رعاية|تنظيم|برنامج).*?الدولي'],
        'exclusion_patterns': ['\\bKuwait\\s+Region\\b', '\\bKuwait\\s+countries\\b', 'بورصة.*?الدولي', 'أسواق.*?الدولي'],
        'common_contexts': ['Islamic banking', 'International banking', 'Corporate finance', 'Investment banking'],
        'validation_status': 'READY'
    },
    'abk': {
        'official_english': 'Al Ahli Bank of Kuwait',
        'english_name': 'Al Ahli Bank of Kuwait',
        'official_arabic': 'البنك الأهلي الكويتي',
        'arabic_name': 'البنك الأهلي الكويتي',
        'abbreviations': ['ABK', 'A.B.K.', 'الأهلي'],
        'high_confidence_patterns': ['\\bAl\\ Ahli\\ Bank\\ of\\ Kuwait\\b', 'البنك\\ الأهلي\\ الكويتي', '"البنك\\ الأهلي\\ الكويتي"', '"Al\\ Ahli\\ Bank\\ of\\ Kuwait"', '\\bABK\\b', '\\bA\\.B\\.K\\.\\b', '\\bالأهلي\\b', '\\bAl\\ Ahli\\ Bank\\ of\\ Kuwait\\s+Sponsorship\\b', 'البنك\\ الأهلي\\ الكويتي\\s+رعاية', 'رعاية.*?البنك\\ الأهلي\\ الكويتي', '«ABK».*?(?:بنك|مصرف|رعا)'],
        'medium_confidence_patterns': ['\\bAl\\s+Kuwait\\b', '\\bAl\\s+Ahli\\s+Kuw\\b', 'الكويتي.*?(?:اختتم|افتتح|تنظيم|رعاية)', '(?:اختتم|افتتح|تنظيم|رعاية).*?الكويتي', '(?:رعاية|تنظيم|برنامج).*?الكويتي'],
        'exclusion_patterns': ['\\bAl\\s+Region\\b', '\\bAl\\s+countries\\b', 'بورصة.*?الكويتي', 'أسواق.*?الكويتي'],
        'common_contexts': ['Retail banking', 'Personal finance', 'SME banking', 'Digital services'],
        'validation_status': 'READY'
    },
    'warba_bank': {
        'official_english': 'Warba Bank',
        'english_name': 'Warba Bank',
        'official_arabic': 'بنك وربة',
        'arabic_name': 'بنك وربة',
        'abbreviations': ['Warba', 'وربة'],
        'high_confidence_patterns': ['\\bWarba\\ Bank\\b', 'بنك\\ وربة', '"بنك\\ وربة"', '"Warba\\ Bank"', '\\bWarba\\b', '\\bوربة\\b', '\\bWarba\\ Bank\\s+Sponsorship\\b', 'بنك\\ وربة\\s+رعاية', 'رعاية.*?بنك\\ وربة', '«Warba».*?(?:بنك|مصرف|رعا)'],
        'medium_confidence_patterns': ['\\bWarba\\s+Bank\\b', 'وربة.*?(?:اختتم|افتتح|تنظيم|رعاية)', '(?:اختتم|افتتح|تنظيم|رعاية).*?وربة', '(?:رعاية|تنظيم|برنامج).*?وربة'],
        'exclusion_patterns': ['\\bWarba\\s+Region\\b', '\\bWarba\\s+countries\\b', 'بورصة.*?وربة', 'أسواق.*?وربة'],
        'common_contexts': ['Islamic banking', 'Digital banking', 'Youth banking', 'Innovative banking'],
        'validation_status': 'READY'
    },
}

def get_all_search_patterns(bank_code):
    """Get combined search patterns for a bank"""
    if bank_code not in BANK_CONFIGS:
        return []
    
    config = BANK_CONFIGS[bank_code]
    return config['high_confidence_patterns'] + config['medium_confidence_patterns']

def get_exclusion_patterns(bank_code):
    """Get exclusion patterns for a bank"""
    if bank_code not in BANK_CONFIGS:
        return []
    
    return BANK_CONFIGS[bank_code]['exclusion_patterns']

def get_bank_info(bank_code):
    """Get basic bank information"""
    if bank_code not in BANK_CONFIGS:
        return None
    
    config = BANK_CONFIGS[bank_code]
    return {
        'english_name': config['english_name'],
        'arabic_name': config['arabic_name'],
        'abbreviations': config['abbreviations']
    }

def get_all_bank_codes():
    """Get list of all available bank codes"""
    return list(BANK_CONFIGS.keys())

def get_active_banks():
    """Get list of banks with ACTIVE status"""
    return [code for code, config in BANK_CONFIGS.items() 
            if config['validation_status'] == 'ACTIVE']

def validate_bank_patterns():
    """Validate that all bank configurations are properly structured"""
    required_fields = ['english_name', 'arabic_name', 'abbreviations', 
                      'high_confidence_patterns', 'medium_confidence_patterns', 'exclusion_patterns']
    
    for bank_code, config in BANK_CONFIGS.items():
        for field in required_fields:
            if field not in config:
                print(f"❌ Missing field '{{field}}' in {{bank_code}} configuration")
                return False
    
    print("✅ All bank configurations are valid")
    return True

if __name__ == "__main__":
    print("🏦 Bank Patterns Configuration")
    print("=" * 50)
    validate_bank_patterns()
    print(f"📊 Available Banks: {{len(BANK_CONFIGS)}}")
    for bank_code, config in BANK_CONFIGS.items():
        status_icon = "🟢" if config['validation_status'] == 'ACTIVE' else "🟡"
        print(f"   {{status_icon}} {{bank_code}}: {{config['english_name']}}")
